module.exports = {
  extends: 'eslint:all',
  rules: {
    'array-bracket-newline': ['error', 'consistent'],
    'array-element-newline': ['error', 'consistent'],
    'arrow-parens': ['error', 'as-needed'],
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'capitalized-comments': 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'complexity': 'off',
    'curly': ['error', 'multi-line'],
    'dot-location': ['error', 'property'],
    'func-names': ['error', 'as-needed'],
    'func-style': 'off',
    'function-call-argument-newline': ['error', 'consistent'],
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'id-length': 'off',
    'indent': ['error', 2],
    'line-comment-position': 'off',
    'linebreak-style': 'off',
    'lines-around-comment': 'off',
    'lines-between-class-members': ['error', 'never'],
    'max-len': ['error', { code: 200, tabWidth: 2 }],
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'max-statements-per-line': 'off',
    'max-statements': 'off',
    'multiline-comment-style': 'off',
    'multiline-ternary': ['error', 'always-multiline'],
    'no-bitwise': 'off',
    'no-empty-function': 'off',
    'no-inline-comments': 'off',
    'no-magic-numbers': 'off',
    'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
    'no-nested-ternary': 'off',
    'no-plusplus': 'off',
    'no-ternary': 'off',
    'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    'no-warning-comments': 'off',
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'one-var': ['error', 'never'],
    'one-var-declaration-per-line': ['error', 'always'],
    'operator-linebreak': ['error', 'after', { 'overrides': { '?': 'before', ':': 'before' } }],
    'padded-blocks': ['error', 'never'],
    'padding-line-between-statements': [
      'error',
      // imports always grouped and separate from the rest
      { blankLine: 'always', prev: 'import', next: '*' },
      { blankLine: 'always', prev: '*', next: 'import' },
      { blankLine: 'never', prev: 'import', next: 'import' },
      { blankLine: 'always', prev: 'cjs-import', next: '*' },
      { blankLine: 'always', prev: '*', next: 'cjs-import' },
      { blankLine: 'never', prev: 'cjs-import', next: 'cjs-import' },
      { blankLine: 'never', prev: 'import', next: 'cjs-import' },
      { blankLine: 'never', prev: 'cjs-import', next: 'import' },
    ],
    'quote-props': ['error', 'consistent'],
    'quotes': ['error', 'single'],
    'semi': ['error', 'never'],
    'sort-imports': 'off',
    'sort-keys': 'off',
    'space-before-function-paren': ['error', { anonymous: 'never', asyncArrow: 'always', named: 'never' }],
    'strict': ['error', 'never'],
  },
}
