module.exports = {
  extends: [
    'plugin:react/all',
    'plugin:react-hooks/recommended',
  ],
  rules: {
    'react-hooks/exhaustive-deps': 'off',
    'react/destructuring-assignment': 'off',
    'react/forbid-dom-props': 'off',
    'react/forbid-elements': 'off',
    'react/function-component-definition': 'off',
    'react/jsx-indent': ['error', 2],
    'react/jsx-indent-props': ['error', 2],
    'react/jsx-filename-extension': 'off',
    'react/jsx-max-depth': 'off',
    'react/jsx-max-props-per-line': 'off',
    'react/jsx-newline': 'off',
    'react/jsx-no-bind': 'off',
    'react/jsx-no-literals': 'off',
    'react/jsx-one-expression-per-line': ['error', { 'allow': 'single-child' }],
    'react/jsx-sort-default-props': 'off',
    'react/jsx-sort-props': 'off',
    'react/no-array-index-key': 'off',
    'react/no-set-state': 'off',
    'react/prefer-read-only-props': 'off',
    'react/prefer-stateless-function': 'off',
    'react/prop-types': 'off',
    'react/require-optimization': 'off',
    'react/sort-prop-types': 'off',
    'react/static-property-placement': 'off',
  },
}
